name: Matrix Testing

on:
  push:
    branches:
      - '**'

jobs:
  matrix-testing:
    strategy:
      fail-fast: false
      matrix:
        maven: [ 3.5.2, 3.9.6, 4.0.0-alpha-13]
        os: [ ubuntu-latest, windows-latest ]
        java: [11, 17, 21]
        exclude:
          - java: 11
            maven: 4.0.0-alpha-13
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '${{ matrix.java }}'
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: '${{ matrix.maven }}'
      - name: Maven verify
        run: mvn -B verify
